# originally based on https://github.com/alexarchambault/mill-native-image/blob/dca83cef17f1a90360b62610e1dcce57271ef37d/.github/workflows/ci.yml

name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1
      with:
        jvm: 8
    - name: Test
      run: ./mill __.test

  publish:
    if: github.event_name == 'push' && github.repository == 'coursier/mill-cs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1
      with:
        jvm: 8
    - run: .github/scripts/gpg-setup.sh
      env:
        PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
    - name: Release
      run: ./mill publishSonatype __.publishArtifacts
      env:
        PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
